---
grails:
    profile: web
    codegen:
        defaultPackage: shareshopping
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            form: application/x-www-form-urlencoded
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: josn
server:
    servlet:
        context-path: /share
---
environments:
    development:
        grails:
            mongodb:
                host: 123.56.45.131
                port: 27017
                databaseName: beta
                options:
                    connectionsPerHost: 100
                    threadsAllowedToBlockForConnectionMultiplier: 5
                    maxWaitTime: 120000
                    connectTimeout: 6000
                    socketTimeout: 60000
                    socketKeepAlive: true
                    #readPreference: secondaryPreferred
    beta:
        grails:
            mongodb:
                host: 123.56.45.131
                port: 27017
                databaseName: beta
                options:
                    connectionsPerHost: 100
                    threadsAllowedToBlockForConnectionMultiplier: 5
                    maxWaitTime: 120000
                    connectTimeout: 6000
                    socketTimeout: 60000
                    socketKeepAlive: true
                    #readPreference: secondaryPreferred
    production:
        grails:
            mongodb:
                host: 123.56.45.131
                port: 27017
                databaseName: prod
                options:
                    connectionsPerHost: 100
                    threadsAllowedToBlockForConnectionMultiplier: 5
                    maxWaitTime: 120000
                    connectTimeout: 6000
                    socketTimeout: 60000
                    socketKeepAlive: true
                    #readPreference: secondaryPreferred
